[metadata]
name = pyvpn
version = 2.0.0
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.8
install_requires =
    cryptography>=41.0

[options.packages.find]
include =
    pyvpn
    pyvpn.*

[options.extras_require]
scraping =
    requests>=2.31
    httpx>=0.25
dev =
    requests>=2.31
    httpx>=0.25
    playwright>=1.40
    pytest>=7.0
    pytest-asyncio>=0.21

[options.entry_points]
console_scripts =
    pyvpn-server   = pyvpn.server:_main
    pyvpn-client   = pyvpn.client_cli:_main
    pyvpn-gencerts = pyvpn.certs:_main

[bdist_wheel]
universal = 0

[flake8]
max-line-length = 100
extend-ignore = E501,W503
